import 'strategy_product.dart';

class StrategyMockData {
  static List<StrategyProduct> products() {
    return const [
      StrategyProduct(
        id: 'range-income',
        name: '区间收益增强',
        shortDescription: '在价格来回波动时，系统自动分批买入/卖出，争取累积收益。',
        riskNote: '短期波动可能较大，收益不保证。',
        performance3mPercentSeries: [
          0,
          0.6,
          1.1,
          0.9,
          0.7,
          0.8,
          1.4,
          2.0,
          1.6,
          1.2,
          1.0,
          1.3,
          2.2,
          2.9,
          2.6,
          2.4,
          2.7,
          3.4,
          4.1,
          3.7,
          3.2,
          3.5,
          4.4,
          5.2,
          4.8,
          5.0,
          5.8,
          6.4,
        ],
        annualizedReturnPercent: 18.6,
        investorCount: 12842,
        aumUsd: 1240000,
        suitableFor: ['能接受中等波动，希望获取更平滑的收益体验', '愿意长期持有并让系统自动执行'],
        notSuitableFor: ['希望短期必赚或不能接受回撤', '需要随时手动干预每一次交易'],
      ),
      StrategyProduct(
        id: 'steady-invest',
        name: '稳健定投计划',
        shortDescription: '按固定周期小额投入，帮助你降低择时压力。',
        riskNote: '定投也可能遇到下跌期，请做好长期准备。',
        performance3mPercentSeries: [
          0,
          0.1,
          0.0,
          0.2,
          0.35,
          0.4,
          0.32,
          0.28,
          0.3,
          0.45,
          0.55,
          0.6,
          0.52,
          0.5,
          0.58,
          0.7,
          0.82,
          0.75,
          0.68,
          0.72,
          0.9,
          1.05,
          0.95,
          0.9,
          1.1,
          1.25,
          1.15,
          1.3,
          1.45,
          1.7,
        ],
        annualizedReturnPercent: 11.2,
        investorCount: 34110,
        aumUsd: 5320000,
        suitableFor: ['不想频繁盯盘，希望用固定节奏慢慢积累', '偏好相对稳定的执行方式'],
        notSuitableFor: ['追求短期高收益', '无法接受阶段性亏损'],
      ),
      StrategyProduct(
        id: 'dip-catcher',
        name: '回调机会捕捉',
        shortDescription: '当价格出现明显偏离时，系统尝试分批介入并设置止盈/止损。',
        riskNote: '更偏进攻，波动与回撤可能更高。',
        performance3mPercentSeries: [
          0,
          -1.4,
          -0.9,
          -0.2,
          0.9,
          0.4,
          -0.6,
          0.8,
          2.0,
          1.2,
          0.5,
          1.6,
          3.0,
          2.1,
          1.2,
          2.6,
          4.5,
          3.2,
          2.0,
          3.8,
          6.0,
          4.6,
          3.5,
          5.4,
          7.8,
          6.2,
          5.0,
          7.1,
          9.6,
        ],
        annualizedReturnPercent: 24.9,
        investorCount: 6230,
        aumUsd: 860000,
        suitableFor: ['能接受较大波动，追求更高潜在收益', '愿意理解基本风险提示并坚持执行'],
        notSuitableFor: ['风险承受能力较低', '无法接受短期大幅波动'],
      ),
    ];
  }
}
